name: 'Terragrunt CI/CD'

on:
  push:
    paths:
    - 'terraform/deployments/**'
    branches:
    - main
  pull_request:
    paths:
    - 'terraform/deployments/**'
    branches:
    - main

jobs:
  terragrunt_plan:
    name: 'Terragrunt Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    # - name: Checkout code
    #   uses: actions/checkout@v2

    # Fetch the main branch to compare
    - name: Fetch main branch
      run: git fetch origin main

    - name: 'Debug'
      run: |
        ls
        git branch --show-current
        git rev-parse 'HEAD^1'
        prev_commit=$(git rev-parse 'HEAD^1')
        git diff --name-only --diff-filter=d $prev_commit terraform/deployments| xargs -r dirname | sort | uniq
        variable_low=$(git diff --name-only --diff-filter=d $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        variable_high=$(git diff --name-only --diff-filter=d $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        echo "variable_low = ${variable_low}"
        echo "variable_low = $variable_low"
        echo "variable_high = ${variable_high}"
        echo "variable_high = $variable_high"
      shell: bash

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11 # Specify your desired Terraform version

    - name: 'Install Terragrunt'
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.0/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Set up gcloud CLI'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: 'Terragrunt Plan Apply'
      run: |
        prev_commit=$(git rev-parse 'HEAD^1')
        modified_dirs=$(git diff --name-only --diff-filter=d $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        for dir in $modified_dirs; do
          (
            cd $dir
            terragrunt plan -out=tfplan
          )
        done
      shell: bash

    - name: 'Terragrunt Plan Destroy'
      run: |
        prev_commit=$(git rev-parse 'HEAD^1')
        deleted_dirs=$(git diff --name-only --diff-filter=D $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        for dir in $deleted_dirs; do
          (
            cd $dir
            terragrunt plan -out=tfplan
          )
        done
      shell: bash

  terragrunt_apply:
    name: 'Terragrunt Apply'
    needs: terragrunt_plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # if: github.ref == 'refs/heads/main'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: 'Install Terragrunt'
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.0/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Set up gcloud CLI'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: 'Run Terragrunt Apply'
      run: |
        prev_commit=$(git rev-parse 'HEAD^1')
        modified_dirs=$(git diff --name-only --diff-filter=d $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        for dir in $modified_dirs; do
          (
            cd $dir
            terragrunt apply -auto-approve tfplan
          )
        done
      shell: bash

  terragrunt_destroy:
    name: 'Terragrunt Destroy'
    needs: terragrunt_plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: 'Install Terragrunt'
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.0/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: 'Set up gcloud CLI'
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: 'Run Terragrunt Destroy'
      run: |
        prev_commit=$(git rev-parse 'HEAD^1')
        deleted_dirs=$(git diff --name-only --diff-filter=D $prev_commit terraform/deployments| xargs -r dirname | sort | uniq)
        for dir in $deleted_dirs; do
          (
            cd $dir
            terragrunt destroy -auto-approve
          )
        done
      shell: bash
